/**
 * KidTok WebView Face AR v6 — real face aging (Snapchat/Instagram-style) +
 * cohesive 3D accessory models, all local files (no bridge streaming).
 *
 * Tracking engine: `@mediapipe/tasks-vision`'s `FaceLandmarker` (VIDEO mode).
 * Verified via direct inspection of the shipped bundle (not assumed from
 * docs) that it exports `FaceLandmarker`/`FilesetResolver`/`ImageSegmenter`,
 * and its result includes `faceBlendshapes` (52 ARKit-style categories,
 * e.g. browDownLeft, mouthSmileLeft). We keep computing the head rig
 * (position/quaternion/faceWidth) from raw landmarks ourselves — proven code,
 * unrelated to which model produced the landmarks.
 *
 * CURRENT MILESTONE (v6): the grandpa filter is reduced to EXACTLY one thing
 * — a live face mesh, built from Google's official canonical_face_model.obj
 * (468 verts, UV coords, 898 tris — embedded as __CANONICAL_FACE__,
 * generated by parsing the real .obj file, no guessed data), showing the
 * REAL camera pixels with a wrinkle texture blended on top. No hair, no
 * accessory, no procedural geometry of any kind is attached to this filter
 * — `FILTERS.grandpa` has neither `url` nor `build`; `showFilter()` skips
 * the accessory-template path entirely for `kind:'aging'`. Geometric
 * deformation is LIVE via the generic morph engine (buildMorphOffsets +
 * GRANDPA_MORPH config): static per-vertex face-local offsets computed
 * procedurally from the canonical mesh, applied in the vertex shader,
 * rotated with the tracked head, mastered by the ageAmount uniform.
 *
 * How the wrinkle texture stays glued to the face: every frame, the mesh's
 * vertex positions are set directly from the 468 live landmarks (buffer slot
 * → landmark index mapping verified 1:1, zero seam duplication needed); its
 * UV attribute never changes, so a wrinkle texture painted in that UV space
 * stays on the same skin region (forehead stays forehead, etc.) as the face
 * moves/turns/tilts — that is what "UV texture mapping" + "canonical face
 * mesh" means concretely in this file. The fragment shader ONLY changes
 * pixel color (see the comment directly above its uniforms below for why it
 * cannot move geometry); the wrinkle mask is packed into RGB channels:
 * R = always-on (crow's feet, under-eye), G = forehead furrows (scaled by
 * the browDown blendshape), B = nasolabial folds (scaled by mouthSmile) —
 * real MediaPipe expression data, not a heuristic.
 *
 * Orientation note: both the video texture and the wrinkle canvas texture
 * are explicitly `flipY = false`, matching MediaPipe's landmark coordinates
 * (top-left-origin image space, same as this file's own lmToScreen — it
 * never flips lm.y) and the canonical model's raw (unflipped) UV values —
 * ONE consistent convention end to end, instead of an earlier version that
 * flipped the UV in the Python preprocessing step AND set flipY=true on the
 * texture, which could combine incorrectly. If the very first on-device
 * test shows the skin texture upside-down or mirrored against the tracked
 * mesh, that is a one-line fix (toggle flipY on videoTexture/wrinkleTexture
 * below), not a pipeline problem.
 *
 * Hair segmentation is NOT implemented in this file at all right now (not
 * even as a placeholder) — MediaPipe does ship an official
 * `hair_segmenter.tflite` (verified downloadable, 781KB) for real per-pixel
 * hair segmentation; wiring it up is a separate, larger change (a second
 * model load + a second per-frame inference pass) intentionally left out
 * until the wrinkle-texture milestone above is confirmed working on-device.
 *
 * Protocol (unchanged):
 *   RN → Web : {type:'setAnimal', id} | {type:'record', on} | {type:'flip'}
 *            | {type:'destroy'}
 *   Web → RN : {type:'ready'} | {type:'loading', label} | {type:'error', message}
 *            | {type:'videoStart'} | {type:'videoChunk', index, total, data}
 *            | {type:'videoDone', mime, size} | {type:'tracking', found}
 *            | {type:'filterReady', id} | {type:'filterError', id, message}
 */
import { AR_MODELS } from './arModels'
import canonicalFaceMesh from './canonicalFaceMesh.json'

export const WEB_AR_INDEX_FILE = 'index.html'

// The avatar-recording flow is now a focused AGE-TRANSFORMATION experience:
// The picker contains only filters that are rendered from our landmark-aware
// runtime. Archive GLBs are intentionally not exposed: their pivots were not
// authored for a live face rig and produced floating/eye-covering results.
export const WEB_AR_FILTERS = [
  { id: 'grandpa', emoji: '👴', nameAr: 'جدو', nameEn: 'Grandpa', color: '#94A3B8' },
  { id: 'cat_ears', emoji: '🐱', nameAr: 'قطة', nameEn: 'Cat', color: '#FB7185' },
  { id: 'rabbit_ears', emoji: '🐰', nameAr: 'أرنب', nameEn: 'Rabbit', color: '#F472B6' },
  { id: 'glasses', emoji: '👓', nameAr: 'نظارة', nameEn: 'Glasses', color: '#38BDF8' },
] as const
export type WebArAnimal = (typeof WEB_AR_FILTERS)[number]['id']
export const WEB_AR_ANIMALS = WEB_AR_FILTERS.map((f) => f.id)

/** Which filter opens by default per catalog avatar. */
export const AVATAR_TO_WEB_ANIMAL: Record<string, string> = {
  boy: 'grandpa',
  king: 'grandpa',
  grandpa: 'grandpa',
}

// Baked into the page at generation time — the only data crossing the RN↔Web
// boundary for models/mesh data is this small static JSON, embedded once in
// the HTML string below. No postMessage, no base64, no per-model round-trip.
const AR_MODELS_META = JSON.stringify(
  AR_MODELS.map((m) => ({ id: m.id, file: m.file, offset: m.offset, width: m.width, rotate: m.rotate })),
)
const CANONICAL_FACE_META = JSON.stringify(canonicalFaceMesh)

export const WEB_AR_HTML = /* html */ `<!DOCTYPE html>
<html lang="ar">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<style>
  html, body { margin:0; padding:0; width:100%; height:100%; overflow:hidden; background:#000; }
  #cam { position:fixed; inset:0; width:100%; height:100%; object-fit:cover; background:#000; }
  #cam.mirrored { transform: scaleX(-1); }
  #gl { position:fixed; inset:0; width:100%; height:100%; }
</style>
<script type="importmap">
{
  "imports": {
    "three": "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js",
    "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/",
    "d3-delaunay": "https://cdn.jsdelivr.net/npm/d3-delaunay@6/+esm",
    "@mediapipe/tasks-vision": "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.9/vision_bundle.mjs"
  }
}
</script>
</head>
<body>
<video id="cam" class="mirrored" autoplay muted playsinline></video>
<canvas id="gl"></canvas>
<script>
  window.__AR_MODELS__ = ${AR_MODELS_META}
  window.__CANONICAL_FACE__ = ${CANONICAL_FACE_META}
  // Set as soon as teardown starts (pagehide, explicit {type:'destroy'}, or a
  // fatal boot error). Checked by rnPost and by every async continuation so
  // nothing touches the (possibly gone) native bridge after destruction.
  window.__kidtokDestroyed = false
  function rnPost(payload) {
    if (window.__kidtokDestroyed) return
    try {
      // window.__WEB_AR_RUNTIME__ does not exist yet for the first couple of
      // boot messages (it is created once the module script below runs) —
      // every message from that point on carries the id so RN-side logs can
      // tell, definitively, whether more than one runtime is talking to it.
      const runtime = window.__WEB_AR_RUNTIME__
      const stamped = Object.assign({}, payload, { runtimeInstanceId: runtime ? runtime.runtimeInstanceId : null })
      if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage(JSON.stringify(stamped))
    } catch (e) {}
  }
  window.onerror = function (message, source, line) {
    rnPost({ type: 'error', message: String(message) + ' @' + (source || '') + ':' + line })
  }
  window.addEventListener('unhandledrejection', function (e) {
    rnPost({ type: 'error', message: 'unhandled: ' + String(e.reason && e.reason.message || e.reason) })
  })
  rnPost({ type: 'loading', label: 'boot' })
  window.__kidtokQueue = []
  window.__kidtokHandle = function (raw) { window.__kidtokQueue.push(raw) }
  function listenRN(event) { window.__kidtokHandle(event.data) }
  window.addEventListener('message', listenRN)
  document.addEventListener('message', listenRN)
</script>

<script type="module">
import * as THREE from 'three'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js'
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js'
import * as BufferGeometryUtils from 'three/addons/utils/BufferGeometryUtils.js'
import { Delaunay } from 'd3-delaunay'
import { FaceLandmarker, FilesetResolver } from '@mediapipe/tasks-vision'

function isDestroyed() { return window.__kidtokDestroyed === true }

// ── Landmarks used for the head rig (tracking only — never drawn) ───────────
const LM = { noseTip: 1, forehead: 10, chin: 152, templeL: 234, templeR: 454, between: 168, lipTop: 13, lipBottom: 14 }
// Hairline arc — used only to size/aim the procedural hair-cap accessory,
// not for any per-vertex live tracking.
const SCALP = [21, 54, 103, 67, 109, 10, 338, 297, 332, 284, 251]

const videoEl = document.getElementById('cam')
const glCanvas = document.getElementById('gl')

let facing = 'user'
let currentFilter = 'grandpa'
let faceLandmarker = null
let videoStream = null
let latestResult = null
let latestLandmarks = null
let trackingFound = null
// Framebuffer-clear investigation: how many upcoming loop() frames should
// still post pre/post-render diagnostics. Set by clearActiveFilter() so the
// frames right after a filter switch are the ones actually inspected,
// instead of every frame for the whole session (which would flood the
// postMessage bridge at ~30-60 msg/sec for no benefit once the picture is
// already clean).
let renderDiagFramesRemaining = 0

function countFilterOwned() {
  let n = 0
  scene.traverse((obj) => {
    if (obj.userData && obj.userData.filterOwned === true) n++
  })
  return n
}

let rafId = 0
// Incremented once per startAR() call, right before its loop()'s first
// frame. Each loop() closure captures its own generation number and
// self-cancels if a newer one has since started — this is what guarantees
// only one active requestAnimationFrame loop even if startAR() were ever
// (incorrectly) called twice in the same runtime.
let animationLoopGeneration = 0
let detectTimestamp = 0

let recorder = null
let recordedChunks = []
let compositeCanvas = null
let compositeCtx = null
let compositeStream = null
let micStream = null
let audioCtx = null
let recDest = null

// ── Device tier ─────────────────────────────────────────────────────────────
function gpuTier() {
  try {
    const probe = document.createElement('canvas')
    if (probe.getContext('webgl2')) return 2
    if (probe.getContext('webgl')) return 1
    return 0
  } catch (e) { return 0 }
}
const TIER = gpuTier()
if (TIER === 0) rnPost({ type: 'error', message: 'no-webgl' })
const PIXEL_RATIO = Math.min(window.devicePixelRatio || 1, TIER === 2 ? 2 : 1.25)
const PROCESS_EVERY = TIER === 2 ? 1 : 2   // ~30fps vs ~15fps tracking

// HD camera for display/recording; tracking runs on a 352px copy.
const realGUM = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices)
navigator.mediaDevices.getUserMedia = (constraints) => {
  const patched = Object.assign({}, constraints)
  if (patched.video) {
    const video = typeof patched.video === 'object' ? Object.assign({}, patched.video) : {}
    video.facingMode = facing
    video.width = { ideal: 1280 }
    video.height = { ideal: 720 }
    patched.video = video
  }
  return realGUM(patched)
}
const procCanvas = document.createElement('canvas')
const procCtx = procCanvas.getContext('2d', { willReadFrequently: true })
function trackingFrame() {
  const vw = videoEl.videoWidth, vh = videoEl.videoHeight
  if (!vw || !vh) return null
  const targetW = 352
  const targetH = Math.round(targetW * (vh / vw))
  if (procCanvas.width !== targetW || procCanvas.height !== targetH) {
    procCanvas.width = targetW
    procCanvas.height = targetH
  }
  procCtx.drawImage(videoEl, 0, 0, targetW, targetH)
  return procCanvas
}

// ── Runtime singleton guard ──────────────────────────────────────────────
// Diagnostic response to: clearActiveFilter() proves the active scene has
// zero filter-owned objects (filterOwnedRemaining: 0) yet the crown/cat
// stay visible on screen. That only makes sense if some OTHER renderer/
// canvas/scene is also drawing — either this module script somehow running
// twice in one document, or a second native WebView instance stacked by
// React Native (invisible to this page's own DOM/JS, see WebArRecorder.tsx
// mount/unmount logging for that half of the investigation). This block
// makes the in-page half of that provable and, defensively, impossible: a
// unique id per boot attached to every diag message, real counts of
// canvases/renderers/scenes, and a full teardown of any previous runtime
// record before this one creates anything.
function generateRuntimeInstanceId() {
  try {
    if (window.crypto && typeof window.crypto.randomUUID === 'function') return window.crypto.randomUUID()
  } catch (e) {}
  return 'rt_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 10)
}
const runtimeInstanceId = generateRuntimeInstanceId()
window.__WEB_AR_INIT_COUNT__ = (window.__WEB_AR_INIT_COUNT__ || 0) + 1
const WEB_AR_INIT_COUNT = window.__WEB_AR_INIT_COUNT__

/**
 * If window.__WEB_AR_RUNTIME__ already holds a live (non-destroyed) record
 * — this module script executing again in the SAME document/realm — fully
 * tear it down before the new renderer/scene below is created. In normal
 * operation (module scripts evaluate once per document) this previous
 * record is always null and the function is a no-op; it exists so two
 * renderers/canvases/animation loops can never coexist in one page even if
 * that assumption is ever violated (e.g. a future injectJavaScript re-run).
 */
function destroyPreviousRuntimeIfAny() {
  const prev = window.__WEB_AR_RUNTIME__
  if (!prev || prev.destroyed) return
  try { if (prev.animationFrameId) cancelAnimationFrame(prev.animationFrameId) } catch (e) {}
  try { if (prev.renderer) prev.renderer.setAnimationLoop(null) } catch (e) {}
  try {
    const gl = prev.renderer && prev.renderer.getContext && prev.renderer.getContext()
    const ext = gl && gl.getExtension && gl.getExtension('WEBGL_lose_context')
    if (ext) ext.loseContext()
  } catch (e) {}
  try { if (prev.renderer) prev.renderer.dispose() } catch (e) {}
  try {
    if (prev.renderer && prev.renderer.domElement && prev.renderer.domElement.parentNode && prev.renderer.domElement !== glCanvas) {
      prev.renderer.domElement.parentNode.removeChild(prev.renderer.domElement)
    }
  } catch (e) {}
  prev.destroyed = true
  rnPost({ type: 'diag', stage: 'destroyPreviousRuntime', destroyedRuntimeInstanceId: prev.runtimeInstanceId })
}
destroyPreviousRuntimeIfAny()

/**
 * Temporary debug action (requirement of the duplicate-instance
 * investigation): fully tears down whatever is currently registered, then
 * reloads the page. A real in-place re-init would mean turning this entire
 * module's top-level boot sequence (renderer/scene/camera/lights/loaders/
 * FaceLandmarker/animation loop, ~1000 lines) into a re-entrant function —
 * a much larger, riskier change than this investigation asked for. A reload
 * gives a fresh JS realm, fresh DOM, fresh everything, which is a strictly
 * stronger guarantee of "exactly one fresh runtime" than manually re-running
 * partial init logic while old closures/listeners might still linger.
 */
window.destroyAllWebArInstances = function destroyAllWebArInstances() {
  try { destroyAll() } catch (e) {}
  destroyPreviousRuntimeIfAny()
  rnPost({ type: 'diag', stage: 'destroyAllWebArInstances', action: 'reloading' })
  location.reload()
}

// ── Three.js scene: perspective camera calibrated to screen pixels ──────────
const renderer = new THREE.WebGLRenderer({ canvas: glCanvas, alpha: true, antialias: TIER === 2 })
renderer.setPixelRatio(PIXEL_RATIO)
renderer.outputColorSpace = THREE.SRGBColorSpace
// Explicit, not relying on the implicit default: three.js's WebGLBackground
// sets clearAlpha to 0 automatically when alpha:true is passed to the
// constructor above (verified against the r160 source), so this line does
// not change current behavior — it makes "this canvas must stay transparent
// so the <video id="cam"> element behind it shows through" a real statement
// in the code instead of an easy-to-accidentally-break implicit default.
renderer.setClearColor(0x000000, 0)
const scene = new THREE.Scene()
let W = window.innerWidth, H = window.innerHeight
const FOV = 45
const camera3 = new THREE.PerspectiveCamera(FOV, W / H, 10, 12000)

window.__WEB_AR_RUNTIME__ = {
  runtimeInstanceId,
  scene,
  renderer,
  animationFrameId: null,
  destroyed: false,
  initializationCount: WEB_AR_INIT_COUNT,
}

function describeCanvases() {
  return Array.from(document.querySelectorAll('canvas')).map((c) => ({
    id: c.id || '(no id)',
    className: c.className || '(no class)',
    width: c.width,
    height: c.height,
    parentTagName: c.parentElement ? c.parentElement.tagName : '(no parent)',
    isRendererCanvas: c === renderer.domElement,
  }))
}

rnPost({
  type: 'diag',
  stage: 'runtime-boot',
  webArInitializationCount: WEB_AR_INIT_COUNT,
  canvasCount: document.querySelectorAll('canvas').length,
  canvases: describeCanvases(),
  rendererDomElementId: renderer.domElement.id || '(no id)',
  sceneUuid: scene.uuid,
  animationLoopActive: false, // flips true once loop() starts below (see 'ready' diag)
})

// Environment lighting (PMREM room) makes metals/gems actually shine.
const pmrem = new THREE.PMREMGenerator(renderer)
scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture
const keyLight = new THREE.DirectionalLight(0xffffff, 1.1)
scene.add(keyLight)
scene.add(new THREE.AmbientLight(0xffffff, 0.35))

function resize() {
  W = window.innerWidth; H = window.innerHeight
  renderer.setSize(W, H, false)
  const dist = (H / 2) / Math.tan(THREE.MathUtils.degToRad(FOV / 2))
  camera3.aspect = W / H
  camera3.position.set(W / 2, -H / 2, dist)
  camera3.lookAt(W / 2, -H / 2, 0)
  camera3.updateProjectionMatrix()
  keyLight.position.set(W * 0.15, -H * 0.05, dist * 0.6)
  keyLight.target.position.set(W / 2, -H / 2, 0)
  keyLight.target.updateMatrixWorld()
}
window.addEventListener('resize', resize)
resize()

// ── Landmark → screen mapping (cover crop + selfie mirror) ─────────────────
const _cover = { scale: 1, cropX: 0, cropY: 0, vw: 1280, vh: 720 }
function updateCover() {
  const vw = videoEl.videoWidth || 1280
  const vh = videoEl.videoHeight || 720
  const scale = Math.max(W / vw, H / vh)
  _cover.scale = scale; _cover.vw = vw; _cover.vh = vh
  _cover.cropX = (vw * scale - W) / 2
  _cover.cropY = (vh * scale - H) / 2
}
function lmToScreen(lm, out) {
  let x = lm.x * _cover.vw * _cover.scale - _cover.cropX
  const y = lm.y * _cover.vh * _cover.scale - _cover.cropY
  const z = -lm.z * _cover.vw * _cover.scale
  if (facing === 'user') x = W - x
  out.set(x, -y, z)
  return out
}

// ── Head rig with smoothing ─────────────────────────────────────────────────
const _a = new THREE.Vector3(), _b = new THREE.Vector3(), _c = new THREE.Vector3()
const _right = new THREE.Vector3(), _up = new THREE.Vector3(), _fwd = new THREE.Vector3()
const _basis = new THREE.Matrix4(), _rawQuat = new THREE.Quaternion()

const rig = {
  position: new THREE.Vector3(W / 2, -H / 2, 0),
  quaternion: new THREE.Quaternion(),
  faceWidth: 200,
  fresh: false,   // snap instead of lerp on (re)acquire
}
const POS_ALPHA = 0.45
const ROT_ALPHA = 0.4
const SCALE_ALPHA = 0.3

function updateRig(landmarks) {
  lmToScreen(landmarks[LM.templeL], _a)
  lmToScreen(landmarks[LM.templeR], _b)
  const rawWidth = Math.max(1, _a.distanceTo(_b))
  _right.subVectors(_b, _a).normalize()
  lmToScreen(landmarks[LM.forehead], _a)
  lmToScreen(landmarks[LM.chin], _c)
  _up.subVectors(_a, _c).normalize()
  _fwd.crossVectors(_right, _up).normalize()
  _up.crossVectors(_fwd, _right).normalize()
  _basis.makeBasis(_right, _up, _fwd)
  _rawQuat.setFromRotationMatrix(_basis)
  lmToScreen(landmarks[LM.between], _a)

  if (rig.fresh) {
    rig.position.copy(_a)
    rig.quaternion.copy(_rawQuat)
    rig.faceWidth = rawWidth
    rig.fresh = false
  } else {
    rig.position.lerp(_a, POS_ALPHA)
    rig.quaternion.slerp(_rawQuat, ROT_ALPHA)
    rig.faceWidth += (rawWidth - rig.faceWidth) * SCALE_ALPHA
  }
}

// ── Blendshapes: real expression data from FaceLandmarker (not heuristics) ──
function getBlendshape(name) {
  const cats = latestResult && latestResult.faceBlendshapes && latestResult.faceBlendshapes[0]
    && latestResult.faceBlendshapes[0].categories
  if (!cats) return 0
  for (let i = 0; i < cats.length; i++) {
    if (cats[i].categoryName === name) return cats[i].score || 0
  }
  return 0
}
function browDownAmount() {
  return Math.max(0, Math.min(1, (getBlendshape('browDownLeft') + getBlendshape('browDownRight')) / 2))
}
function smileAmount() {
  return Math.max(0, Math.min(1, (getBlendshape('mouthSmileLeft') + getBlendshape('mouthSmileRight')) / 2))
}

// ── Filter system: ONE cohesive model per filter, cached + cloned ──────────
// FILTERS: id → { url?, build?, rotate?, offset:[x,y,z] (face-widths, head-
// local), width (face-widths) } for accessories, or { kind:'aging' } for the
// live-deformed face-aging effect (handled outside this cache — see
// agingMesh below). GLB models are auto-normalized (centered + scaled)
// after an optional pre-rotation to correct archive-model facing.
const FILTERS = {
  king: {
    build: buildCrownModel,
    offset: [0, 0.58, -0.02],
    width: 1.15,
  },
  // Aging effect: no accessory attached to it at all right now (no hair,
  // no procedural geometry of any kind) — showFilter() skips the
  // template/accessory loading path entirely for 'aging' kind below, per
  // the explicit instruction to isolate the wrinkle-texture-on-live-face
  // milestone with nothing else drawn. See the aging-effect section further
  // down for what actually renders.
  grandpa: {
    kind: 'aging',
  },
}
for (const m of (window.__AR_MODELS__ || [])) {
  FILTERS[m.id] = { url: './' + m.file, offset: m.offset, width: m.width, rotate: m.rotate }
}

const dracoLoader = new DRACOLoader()
dracoLoader.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.6/')
const gltfLoader = new GLTFLoader()
gltfLoader.setDRACOLoader(dracoLoader)

const filterRoot = new THREE.Group()
filterRoot.visible = false
scene.add(filterRoot)

// Cache of NORMALIZED TEMPLATES, one load per id ever, cloned per display —
// satisfies "cache + clone on reselect" without re-fetching or re-parsing.
const modelTemplates = {}     // id → THREE.Object3D (never added to the scene itself)
const modelLoadPromises = {}  // id → in-flight Promise, so concurrent picks share one load

function normalizeModel(object, targetWidth) {
  const box = new THREE.Box3().setFromObject(object)
  const size = box.getSize(new THREE.Vector3())
  const center = box.getCenter(new THREE.Vector3())
  const wrapper = new THREE.Group()
  object.position.sub(center)
  const unit = targetWidth / Math.max(0.0001, size.x)
  wrapper.scale.setScalar(unit)
  wrapper.add(object)
  const outer = new THREE.Group()
  outer.add(wrapper)
  return outer
}

/**
 * Reads a same-origin file:// URL as an ArrayBuffer via XMLHttpRequest.
 * Chromium's fetch() (which THREE.FileLoader/GLTFLoader.loadAsync use
 * internally) rejects the file: scheme outright in Android's WebView —
 * that is the real cause of "TypeError: Failed to fetch" for local .glb
 * loads, NOT a permissions or CORS problem. XHR has always supported
 * file:// reads from a file:// page, so we use it directly and feed the
 * bytes to GLTFLoader.parse() ourselves.
 */
function loadArrayBuffer(url) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', url, true)
    xhr.responseType = 'arraybuffer'
    xhr.onload = () => {
      if (xhr.status === 0 || xhr.status === 200) resolve(xhr.response)
      else reject(new Error('xhr status ' + xhr.status + ' for ' + url))
    }
    xhr.onerror = () => reject(new Error('xhr network error for ' + url))
    xhr.ontimeout = () => reject(new Error('xhr timeout for ' + url))
    xhr.send()
  })
}

async function buildTemplate(id) {
  const def = FILTERS[id]
  if (!def) throw new Error('unknown filter ' + id)
  let object
  if (def.url) {
    const resolvedUrl = new URL(def.url, location.href).href
    rnPost({ type: 'debug', message: 'loading filter ' + id + ' from ' + resolvedUrl })
    let buffer
    try {
      buffer = await loadArrayBuffer(resolvedUrl)
    } catch (e) {
      throw new Error('fetch ' + resolvedUrl + ' failed: ' + (e && e.message || e))
    }
    const gltf = await new Promise((resolve, reject) => {
      gltfLoader.parse(buffer, resolvedUrl, resolve, reject)
    })
    object = gltf.scene || gltf.scenes[0]
  } else if (def.build) {
    object = def.build()
  } else {
    throw new Error('filter ' + id + ' has neither url nor build')
  }
  if (def.rotate) {
    object.rotation.set(def.rotate[0], def.rotate[1], def.rotate[2])
    object.updateMatrixWorld(true)
  }
  return normalizeModel(object, def.width)
}

/** Cached, de-duplicated model load. Never adds anything to the live scene. */
function loadTemplate(id) {
  if (modelTemplates[id]) return Promise.resolve(modelTemplates[id])
  if (modelLoadPromises[id]) return modelLoadPromises[id]
  const promise = buildTemplate(id)
    .then((template) => {
      delete modelLoadPromises[id]
      if (isDestroyed()) return null
      modelTemplates[id] = template
      rnPost({ type: 'filterReady', id })
      return template
    })
    .catch((e) => {
      delete modelLoadPromises[id]
      if (!isDestroyed()) rnPost({ type: 'filterError', id, message: String(e && e.message || e) })
      throw e
    })
  modelLoadPromises[id] = promise
  return promise
}

/**
 * Recursively disposes geometries/materials/textures on an Object3D subtree.
 * Only ever called on objects that are NOT shared with the template cache
 * (see the warning in clearActiveFilter() below) — currently that means:
 * cached accessory templates themselves (at full page teardown) and the
 * aging mesh / occluder (also at teardown). Safe to call on null/undefined.
 */
function disposeObject3D(root) {
  if (!root) return
  root.traverse((obj) => {
    if (obj.geometry) obj.geometry.dispose()
    const mats = Array.isArray(obj.material) ? obj.material : (obj.material ? [obj.material] : [])
    for (const mat of mats) {
      for (const key of Object.keys(mat)) {
        const value = mat[key]
        if (value && value.isTexture) value.dispose()
      }
      mat.dispose()
    }
  })
}

/**
 * Stamps every node of an accessory instance (the clone's own root AND all
 * its descendants — GLB scene nodes, meshes, bones) as belonging to this
 * filter. clearActiveFilter() below trusts this marker, not scene position,
 * to decide what to remove — so an accessory can never survive a switch even
 * if something ends up parented outside filterRoot.
 */
function markFilterOwned(root, id) {
  root.traverse((obj) => {
    obj.userData.filterOwned = true
    obj.userData.filterId = id
  })
}

/**
 * Single point of truth for "nothing from the previous filter may remain."
 * Called at the START of every showFilter(), before anything about the new
 * filter is decided — so no code path can show a new filter without first
 * clearing the old one, whichever kind it was (accessory or aging).
 *
 * Walks the WHOLE scene graph (not just filterRoot) and removes every object
 * carrying userData.filterOwned === true. Camera, lights, agingMesh,
 * occluderMesh and renderer internals are never marked by any code path, so
 * this sweep structurally cannot touch them.
 *
 * IMPORTANT: this does NOT dispose the accessory clones' geometry/material.
 * filterRoot holds a template.clone(true) — Object3D.clone() deep-clones
 * the scene-graph nodes, but each Mesh's geometry/material stay SHARED
 * BY REFERENCE with the cached template in modelTemplates[id] (three.js
 * does this deliberately, precisely so clones are cheap). Disposing a
 * clone's geometry/material would dispose the CACHED template's GPU
 * resources too, permanently breaking that filter the next time it's
 * selected. Real disposal of cached resources only happens once, at full
 * page teardown, in destroyAll() below — that is the technically correct
 * "where appropriate" per the cleanup requirements.
 */
function clearActiveFilter() {
  const found = []
  scene.traverse((obj) => {
    if (obj.userData && obj.userData.filterOwned === true) found.push(obj)
  })
  const markedSet = new Set(found)
  // Only the root of each marked subtree needs an explicit remove() call —
  // removing a node takes its (also-marked) descendants with it for free.
  const roots = found.filter((obj) => !obj.parent || !markedSet.has(obj.parent))

  rnPost({
    type: 'diag',
    stage: 'clearActiveFilter-before',
    activeFilterId: currentFilter,
    filterOwnedObjectsFound: found.length,
    filterOwnedRootsFound: roots.length,
  })

  const removedLog = roots.map((obj) => ({
    name: obj.name || obj.type || '(unnamed)',
    parentName: obj.parent ? (obj.parent.name || obj.parent.type || '(unnamed)') : '(none)',
    filterId: obj.userData.filterId,
  }))
  for (const obj of roots) {
    if (obj.parent) obj.parent.remove(obj)
  }

  filterRoot.visible = false
  if (occluderMesh) occluderMesh.visible = false
  if (agingMesh) agingMesh.visible = false

  let remaining = 0
  scene.traverse((obj) => {
    if (obj.userData && obj.userData.filterOwned === true) remaining++
  })

  rnPost({
    type: 'diag',
    stage: 'clearActiveFilter-after',
    activeFilterId: currentFilter,
    removed: removedLog,
    filterOwnedRemaining: remaining,
  })

  // Framebuffer-clear investigation: force one immediate clean frame right
  // here, synchronously, instead of waiting for the next scheduled
  // requestAnimationFrame. renderer.autoClear is true (three.js default,
  // never overridden anywhere in this file — verified against the r160
  // source), so renderer.render() already clears color/depth/stencil before
  // drawing every frame; this call does not depend on that default staying
  // true, and it means the removed GLB's pixels are gone from the canvas the
  // instant clearActiveFilter() runs, not up to one frame later.
  renderer.clear(true, true, true)
  renderer.render(scene, camera3)
  // Also watch the next few loop() frames' pre/post-render state — see
  // renderDiagFramesRemaining's declaration for why this is capped rather
  // than logged every frame.
  renderDiagFramesRemaining = 3
}

// Monotonic token: a showFilter() call only applies its result if it is still
// the most recent request by the time its (async) load resolves — this is
// what cancels a stale filter switch (e.g. Cat tapped, then King tapped
// before Cat's GLB finishes loading) instead of racing the UI.
let filterRequestVersion = 0

async function showFilter(id) {
  currentFilter = id
  const myVersion = ++filterRequestVersion
  clearActiveFilter()
  const def = FILTERS[id]
  if (def && def.kind === 'aging') {
    // No accessory template at all for the aging effect right now — the
    // render loop drives agingMesh directly every frame (updateAgingMesh),
    // re-showing it since clearActiveFilter() just hid it above.
    rnPost({ type: 'filterReady', id })
    return
  }
  let template
  try {
    template = await loadTemplate(id)
  } catch (e) {
    return // already reported via filterError
  }
  // Superseded by a newer showFilter() while this GLB load/build was in
  // flight, or the page was torn down meanwhile — abort placement, do not
  // add a now-stale accessory on top of whatever the newer call already set.
  if (isDestroyed() || myVersion !== filterRequestVersion) return
  // A newer showFilter() may have run (and cleared) while we were awaiting
  // the load above — clear once more so we never add on top of anything,
  // guaranteeing only one accessory instance is ever live at a time.
  clearActiveFilter()
  if (template) {
    const instance = template.clone(true)
    markFilterOwned(instance, id)
    filterRoot.add(instance)
  }
}

// ── Builtin: royal crown as ONE cohesive merged-geometry model ─────────────
function buildCrownModel() {
  const group = new THREE.Group()

  const goldParts = []
  const bandProfile = []
  for (let i = 0; i <= 24; i++) {
    const t = i / 24
    bandProfile.push(new THREE.Vector2(0.5 + 0.035 * Math.sin(t * Math.PI), t * 0.34))
  }
  const band = new THREE.LatheGeometry(bandProfile, 48)
  goldParts.push(band)

  for (let i = 0; i < 8; i++) {
    const a = (i / 8) * Math.PI * 2
    const tall = i % 2 === 0
    const spike = new THREE.ConeGeometry(tall ? 0.085 : 0.06, tall ? 0.34 : 0.22, 12)
    spike.translate(0, (tall ? 0.34 : 0.22) / 2 + 0.33, 0)
    spike.translate(Math.cos(a) * 0.47, 0, Math.sin(a) * 0.47)
    goldParts.push(spike)
  }
  const rimTop = new THREE.TorusGeometry(0.5, 0.028, 12, 48)
  rimTop.rotateX(Math.PI / 2); rimTop.translate(0, 0.34, 0)
  const rimBase = new THREE.TorusGeometry(0.52, 0.035, 12, 48)
  rimBase.rotateX(Math.PI / 2); rimBase.translate(0, 0.01, 0)
  goldParts.push(rimTop, rimBase)

  const goldGeo = BufferGeometryUtils.mergeGeometries(goldParts, false)
  const gold = new THREE.Mesh(goldGeo, new THREE.MeshStandardMaterial({
    color: 0xE8B44A, metalness: 0.9, roughness: 0.28,
  }))
  group.add(gold)

  const gemA = [], gemB = []
  for (let i = 0; i < 8; i++) {
    const a = (i / 8) * Math.PI * 2 + Math.PI / 8
    const gem = new THREE.SphereGeometry(0.045, 12, 10)
    gem.translate(Math.cos(a) * 0.52, 0.17, Math.sin(a) * 0.52)
    ;(i % 2 === 0 ? gemA : gemB).push(gem)
  }
  const ruby = new THREE.Mesh(BufferGeometryUtils.mergeGeometries(gemA, false), new THREE.MeshStandardMaterial({
    color: 0xE11D48, metalness: 0.1, roughness: 0.12,
  }))
  const sapphire = new THREE.Mesh(BufferGeometryUtils.mergeGeometries(gemB, false), new THREE.MeshStandardMaterial({
    color: 0x2563EB, metalness: 0.1, roughness: 0.12,
  }))
  group.add(ruby, sapphire)

  const velvet = new THREE.Mesh(
    new THREE.CylinderGeometry(0.46, 0.46, 0.3, 32, 1, true),
    new THREE.MeshStandardMaterial({ color: 0x7F1D1D, roughness: 0.9, side: THREE.BackSide }),
  )
  velvet.position.y = 0.16
  group.add(velvet)

  return group
}

// ── Aging effect: LIVE canonical face mesh (real vertex positions every
// frame) + a wrinkle shader sampling the real camera pixels. ───────────────
//
// IMPORTANT correction: the fragment shader below only ever changes PIXEL
// COLOR (the wrinkle darkening) — it cannot and does not move any geometry.
// Actual shape change (sagging jowls, wider/heavier jaw, thinner nose,
// puffy under-eyes) has to happen on the VERTICES, so it is computed here on
// the CPU, once per frame, directly on agingPositions BEFORE it is uploaded
// to the GPU buffer: track the real face → compute per-vertex normals from
// that live shape → push specific landmark groups along normal/down/sideways
// directions by a small amount scaled to faceWidth → upload. That displaced
// geometry is what the vertex shader below then projects to the screen.
const CANONICAL = window.__CANONICAL_FACE__
const AGING_VERTS = CANONICAL.landmarkIndex.length
let agingMesh = null
let agingMaterial = null
// Held at module scope (not only inside material.uniforms) so destroyAll()
// can dispose them explicitly — disposeObject3D()'s isTexture scan walks
// direct material properties, not RawShaderMaterial's nested uniforms.
let wrinkleMaskTexture = null
let detailTexture = null
let cameraVideoTexture = null
const agingPositions = new Float32Array(AGING_VERTS * 3)
const _av = new THREE.Vector3()
const _morphRight = new THREE.Vector3(), _morphUp = new THREE.Vector3(), _morphFwd = new THREE.Vector3()

// ── DEBUG-ONLY topology preview ─────────────────────────────────────────────
// CANONICAL.trianglesFull is the untouched, watertight canonical topology
// (898 faces, closed at eyes/mouth by Google's original design).
// CANONICAL.triangles (852 faces) is the already-shipped pruned mesh. This
// flag makes the pruning an explicit, inspectable, TOGGLEABLE runtime step
// instead of trusting the pre-baked 852 array: when true, the geometry index
// is recomputed live from trianglesFull by dropping any triangle whose three
// vertices all land on one MediaPipe contour ring (official FACEMESH_LIPS /
// FACEMESH_LEFT_EYE / FACEMESH_RIGHT_EYE landmark sets). Flip to false to
// fall back to the static CANONICAL.triangles array untouched.
const DEBUG_TOPOLOGY_PREVIEW = true

const CAP_RING_MOUTH = new Set([13, 14, 78, 80, 81, 82, 87, 88, 95, 178, 191, 308, 310, 311, 312, 317, 318, 324, 402, 415])
const CAP_RING_LEFT_EYE = new Set([249, 263, 362, 373, 374, 380, 381, 382, 384, 385, 386, 387, 388, 390, 398, 466])
const CAP_RING_RIGHT_EYE = new Set([7, 33, 133, 144, 145, 153, 154, 155, 157, 158, 159, 160, 161, 163, 173, 246])

/**
 * Drops any triangle from fullSlotTriangles whose three vertices (mapped
 * through landmarkIndex from internal mesh "slot" to real MediaPipe landmark
 * id) all fall inside one of the eye/mouth contour rings above. Returns the
 * reduced index list plus a per-ring removal count for verification.
 */
function computeOpenTriangles(fullSlotTriangles, landmarkIndex) {
  const kept = []
  let mouthRemoved = 0
  let leftEyeRemoved = 0
  let rightEyeRemoved = 0
  for (let i = 0; i < fullSlotTriangles.length; i += 3) {
    const s0 = fullSlotTriangles[i]
    const s1 = fullSlotTriangles[i + 1]
    const s2 = fullSlotTriangles[i + 2]
    const l0 = landmarkIndex[s0]
    const l1 = landmarkIndex[s1]
    const l2 = landmarkIndex[s2]
    if (CAP_RING_MOUTH.has(l0) && CAP_RING_MOUTH.has(l1) && CAP_RING_MOUTH.has(l2)) { mouthRemoved++; continue }
    if (CAP_RING_LEFT_EYE.has(l0) && CAP_RING_LEFT_EYE.has(l1) && CAP_RING_LEFT_EYE.has(l2)) { leftEyeRemoved++; continue }
    if (CAP_RING_RIGHT_EYE.has(l0) && CAP_RING_RIGHT_EYE.has(l1) && CAP_RING_RIGHT_EYE.has(l2)) { rightEyeRemoved++; continue }
    kept.push(s0, s1, s2)
  }
  return {
    triangles: kept,
    fullCount: fullSlotTriangles.length / 3,
    keptCount: kept.length / 3,
    mouthRemoved,
    leftEyeRemoved,
    rightEyeRemoved,
    totalRemoved: mouthRemoved + leftEyeRemoved + rightEyeRemoved,
  }
}

// Geometric aging is LIVE now — implemented in the aging material's vertex
// shader, driven by the morph engine below (buildMorphOffsets/GRANDPA_MORPH)
// and mastered by the ageAmount uniform (0 = original face, 1 = elderly).

/** WebGL error code → readable name, for diagnostics sent to RN. */
function glErrorName(gl, code) {
  const names = {}
  names[gl.NO_ERROR] = 'NO_ERROR'
  names[gl.INVALID_ENUM] = 'INVALID_ENUM'
  names[gl.INVALID_VALUE] = 'INVALID_VALUE'
  names[gl.INVALID_OPERATION] = 'INVALID_OPERATION'
  names[gl.INVALID_FRAMEBUFFER_OPERATION] = 'INVALID_FRAMEBUFFER_OPERATION'
  names[gl.OUT_OF_MEMORY] = 'OUT_OF_MEMORY'
  if (gl.CONTEXT_LOST_WEBGL !== undefined) names[gl.CONTEXT_LOST_WEBGL] = 'CONTEXT_LOST_WEBGL'
  return names[code] || ('UNKNOWN(' + code + ')')
}

/**
 * Manually compiles+links the exact shader pair as a throwaway raw WebGL
 * program, independent of three.js's own program cache — this is what the
 * requested "shader compile log / shader link log" diagnostics come from.
 * Always runs (not just on failure) so we get real data every time.
 */
function compileDiagnostic(gl, vertSrc, fragSrc) {
  const report = { vertexOk: false, fragmentOk: false, linked: false, vertexLog: '', fragmentLog: '', programLog: '' }
  const vs = gl.createShader(gl.VERTEX_SHADER)
  gl.shaderSource(vs, vertSrc)
  gl.compileShader(vs)
  report.vertexOk = !!gl.getShaderParameter(vs, gl.COMPILE_STATUS)
  report.vertexLog = gl.getShaderInfoLog(vs) || ''

  const fs = gl.createShader(gl.FRAGMENT_SHADER)
  gl.shaderSource(fs, fragSrc)
  gl.compileShader(fs)
  report.fragmentOk = !!gl.getShaderParameter(fs, gl.COMPILE_STATUS)
  report.fragmentLog = gl.getShaderInfoLog(fs) || ''

  const prog = gl.createProgram()
  gl.attachShader(prog, vs)
  gl.attachShader(prog, fs)
  gl.linkProgram(prog)
  report.linked = !!gl.getProgramParameter(prog, gl.LINK_STATUS)
  report.programLog = gl.getProgramInfoLog(prog) || ''

  gl.deleteProgram(prog)
  gl.deleteShader(vs)
  gl.deleteShader(fs)
  return report
}

// ── Generic landmark-driven morph engine ────────────────────────────────────
// Reusable facial deformation: a filter supplies a CONFIG (list of effects,
// each = anchor landmark ids + radius + amplitude + direction), and the
// engine procedurally computes one static per-vertex displacement attribute
// from the canonical mesh — no hand-sculpted per-vertex tables anywhere.
// Directions are expressed in the canonical face basis (x = temple→temple,
// y = chin→forehead, z = out of the face — verified identical to the live
// rig's basis construction), so the vertex shader rotates them with the
// tracked head every frame. Displacement rides ON TOP of the live landmark
// positions, so expressions (smiles etc.) keep working — the morph is a
// constant anatomical offset in face-local space, not a replacement pose.
// Future filters (baby, monster, zombie, fat/thin, beauty) = new configs.
const CANONICAL_POSITIONS = CANONICAL.positions   // 468×3, canonical cm
const SLOT_OF_LANDMARK = (() => {
  const map = {}
  for (let s = 0; s < CANONICAL.landmarkIndex.length; s++) map[CANONICAL.landmarkIndex[s]] = s
  return map
})()
function canonPos(slot, out) {
  out.set(CANONICAL_POSITIONS[slot * 3], CANONICAL_POSITIONS[slot * 3 + 1], CANONICAL_POSITIONS[slot * 3 + 2])
  return out
}
const CANON_TEMPLE_CM = (() => {
  const a = canonPos(SLOT_OF_LANDMARK[234], new THREE.Vector3())
  const b = canonPos(SLOT_OF_LANDMARK[454], new THREE.Vector3())
  return a.distanceTo(b)   // ≈15.33 — the px-per-cm anchor for mm-accurate amplitudes
})()

/** Per-vertex smooth normals of the canonical mesh (procedural, from topology). */
function canonicalNormals(indexTriangles) {
  const n = new Float32Array(468 * 3)
  const pa = new THREE.Vector3(), pb = new THREE.Vector3(), pc = new THREE.Vector3()
  const ab = new THREE.Vector3(), ac = new THREE.Vector3(), fn = new THREE.Vector3()
  for (let i = 0; i < indexTriangles.length; i += 3) {
    const s0 = indexTriangles[i], s1 = indexTriangles[i + 1], s2 = indexTriangles[i + 2]
    canonPos(s0, pa); canonPos(s1, pb); canonPos(s2, pc)
    ab.subVectors(pb, pa); ac.subVectors(pc, pa); fn.crossVectors(ab, ac)
    for (const s of [s0, s1, s2]) {
      n[s * 3] += fn.x; n[s * 3 + 1] += fn.y; n[s * 3 + 2] += fn.z
    }
  }
  const v = new THREE.Vector3()
  for (let s = 0; s < 468; s++) {
    v.set(n[s * 3], n[s * 3 + 1], n[s * 3 + 2])
    // canonical z faces the viewer; normals must point OUT of the face
    if (v.z < 0) v.negate()
    v.normalize()
    n[s * 3] = v.x; n[s * 3 + 1] = v.y; n[s * 3 + 2] = v.z
  }
  return n
}

function smoothFalloff(d, radius) {
  const t = Math.min(1, Math.max(0, d / radius))
  return 1 - t * t * (3 - 2 * t)
}

/**
 * effects: [{ centers: [landmark ids], radiusCm, ampMm, dir: 'in'|'out'|'down' }]
 * 'in'/'out' = along the vertex's own canonical normal (in = volume loss,
 * out = volume gain); 'down' = -y in face space (gravity sag).
 * Protection is fully procedural: every vertex on a topology BOUNDARY edge
 * (face oval + both eye holes + the inner-mouth hole — computed from the
 * index buffer, not listed by hand) plus small zones around the nostrils
 * and eye centers suppress deformation with a soft radial falloff, which
 * covers every "do not deform" region (eyes, eyelids, lips, nostrils,
 * face/forehead outline) without hard transitions.
 */
function buildMorphOffsets(effects, indexTriangles) {
  const edgeCount = {}
  for (let i = 0; i < indexTriangles.length; i += 3) {
    const t0 = indexTriangles[i], t1 = indexTriangles[i + 1], t2 = indexTriangles[i + 2]
    for (const [a, b] of [[t0, t1], [t1, t2], [t2, t0]]) {
      const key = a < b ? a + '_' + b : b + '_' + a
      edgeCount[key] = (edgeCount[key] || 0) + 1
    }
  }
  const boundarySlots = new Set()
  for (const key of Object.keys(edgeCount)) {
    if (edgeCount[key] === 1) {
      const parts = key.split('_')
      boundarySlots.add(parseInt(parts[0], 10))
      boundarySlots.add(parseInt(parts[1], 10))
    }
  }
  const normals = canonicalNormals(indexTriangles)
  const vp = new THREE.Vector3(), cp = new THREE.Vector3(), acc = new THREE.Vector3(), dir = new THREE.Vector3()

  // soft protection field per vertex (1 = fully deformable, 0 = frozen)
  const eyeCenters = []
  for (const ring of [CAP_RING_LEFT_EYE, CAP_RING_RIGHT_EYE]) {
    const c = new THREE.Vector3()
    let count = 0
    ring.forEach((lm) => {
      if (SLOT_OF_LANDMARK[lm] !== undefined) { c.add(canonPos(SLOT_OF_LANDMARK[lm], cp)); count++ }
    })
    if (count) eyeCenters.push(c.multiplyScalar(1 / count))
  }
  const nostrilSlots = [SLOT_OF_LANDMARK[129], SLOT_OF_LANDMARK[358]]
  const protection = new Float32Array(468)
  for (let s = 0; s < 468; s++) {
    canonPos(s, vp)
    let minBoundary = Infinity
    boundarySlots.forEach((bs) => {
      const d = vp.distanceTo(canonPos(bs, cp))
      if (d < minBoundary) minBoundary = d
    })
    let prot = 1 - smoothFalloff(minBoundary, 0.9)      // 0 at boundary → 1 at 0.9cm inside
    for (const ec of eyeCenters) prot *= 1 - smoothFalloff(vp.distanceTo(ec), 1.7)
    for (const ns of nostrilSlots) prot *= 1 - smoothFalloff(vp.distanceTo(canonPos(ns, cp)), 0.7)
    protection[s] = prot
  }

  const out = new Float32Array(468 * 3)
  for (const effect of effects) {
    const ampCm = effect.ampMm / 10
    const centerSlots = effect.centers.map((lm) => SLOT_OF_LANDMARK[lm]).filter((s) => s !== undefined)
    for (let s = 0; s < 468; s++) {
      if (protection[s] <= 0.001) continue
      canonPos(s, vp)
      let minD = Infinity
      for (const cs of centerSlots) {
        const d = vp.distanceTo(canonPos(cs, cp))
        if (d < minD) minD = d
      }
      const w = smoothFalloff(minD, effect.radiusCm) * protection[s]
      if (w <= 0.001) continue
      if (effect.dir === 'down') dir.set(0, -1, 0)
      else {
        dir.set(normals[s * 3], normals[s * 3 + 1], normals[s * 3 + 2])
        if (effect.dir === 'in') dir.negate()
      }
      out[s * 3] += dir.x * ampCm * w
      out[s * 3 + 1] += dir.y * ampCm * w
      out[s * 3 + 2] += dir.z * ampCm * w
    }
  }
  // safety clamp: overlapping zones may sum past the spec — cap at 4mm
  let maxDisp = 0, affected = 0
  for (let s = 0; s < 468; s++) {
    acc.set(out[s * 3], out[s * 3 + 1], out[s * 3 + 2])
    const len = acc.length()
    if (len > 0.4) {
      acc.multiplyScalar(0.4 / len)
      out[s * 3] = acc.x; out[s * 3 + 1] = acc.y; out[s * 3 + 2] = acc.z
    }
    if (len > 0.005) affected++
    if (len > maxDisp) maxDisp = Math.min(len, 0.4)
  }
  return { offsets: out, maxDispMm: maxDisp * 10, affectedVerts: affected, boundaryVerts: boundarySlots.size }
}

// Grandpa: subtle, anatomically-placed volume changes (amplitudes in mm,
// all ≤4mm per the spec; the engine clamps the summed result to 4mm too).
const GRANDPA_MORPH = [
  { centers: [10, 108, 337], radiusCm: 3.0, ampMm: 2.0, dir: 'in' },    // forehead flattening
  { centers: [70, 300, 234, 454], radiusCm: 2.0, ampMm: 2.5, dir: 'in' }, // temple hollowing
  { centers: [50, 280], radiusCm: 2.8, ampMm: 3.5, dir: 'in' },         // cheek volume loss
  { centers: [205, 425], radiusCm: 1.3, ampMm: 2.0, dir: 'in' },        // nasolabial deepening
  { centers: [57, 287], radiusCm: 1.2, ampMm: 2.0, dir: 'down' },       // mouth-corner pull
  { centers: [230, 450], radiusCm: 1.1, ampMm: 2.0, dir: 'out' },       // under-eye bags
  { centers: [136, 365], radiusCm: 2.2, ampMm: 2.0, dir: 'in' },        // jaw softening
  { centers: [136, 365], radiusCm: 2.2, ampMm: 1.2, dir: 'down' },      // jaw sag
  { centers: [199], radiusCm: 1.5, ampMm: 2.0, dir: 'down' },           // chin looseness
]

// ── Wrinkle shading (2D, UV-space only — no geometry deformation yet) ──────
// Start in grayscale debug mode per the milestone requirement: confirm the
// mask itself looks right (right places, right shapes, stable under head
// motion) before judging the blended-over-video look. Flip to false once
// confirmed.
const WRINKLE_DEBUG_MODE = false
// Strength/darkness lowered from 2.0/0.32 per user feedback that the
// on-device result read too dark ("اسود شويه") — uniform-value tuning only,
// the shader math, blending and textures are untouched. Lowering strength
// also proportionally tames the age-spot layer (spotA multiplies it).
const WRINKLE_DEFAULTS = {
  wrinkleStrength: 1.4,
  wrinkleScale: 1.0,
  wrinkleSharpness: 1.0,
  wrinkleDarkness: 0.26,
  wrinkleHighlight: 0.14,
  ageAmount: 1.0,
}

/**
 * Wrinkle placement lives in wrinkle_mask.png now, baked in the exact UV
 * space of canonicalFaceMesh.json from the same MEASURED landmark-derived
 * control points the earlier procedural shader used (eye outer corner,
 * landmark 33 → uv (0.2801, 0.6244); mouth corner, landmark 61 →
 * (0.382, 0.3053); nasolabial 205 → (0.3197, 0.4293); ...). Only the
 * exclusion-ellipse anchors below remain in-shader. Same UV attribute,
 * same per-frame vertex positions — wrinkles track the face exactly like
 * the checker did in the topology milestone.
 */
function ensureAgingMesh() {
  if (agingMesh) return
  try {
    let indexTriangles = CANONICAL.triangles
    let topologyPreview = null
    if (DEBUG_TOPOLOGY_PREVIEW && CANONICAL.trianglesFull) {
      topologyPreview = computeOpenTriangles(CANONICAL.trianglesFull, CANONICAL.landmarkIndex)
      indexTriangles = topologyPreview.triangles
    }

    const geo = new THREE.BufferGeometry()
    geo.setAttribute('position', new THREE.BufferAttribute(agingPositions, 3))
    geo.setAttribute('uv', new THREE.BufferAttribute(new Float32Array(CANONICAL.uv), 2))
    geo.setIndex(new THREE.BufferAttribute(new Uint16Array(indexTriangles), 1))

    const morphBuild = buildMorphOffsets(GRANDPA_MORPH, indexTriangles)
    geo.setAttribute('morph', new THREE.BufferAttribute(morphBuild.offsets, 3))

    // RawShaderMaterial: fully manual GLSL, nothing auto-injected by three.js
    // — removes any ambiguity about what three.js does or doesn't prepend.
    // Geometric aging happens HERE, in the vertex shader only: the static
    // per-vertex morph attribute (face-basis components, canonical cm — see
    // buildMorphOffsets) is rotated by the live head basis and added to the
    // tracked landmark position. uMorphScale = pxPerCm × ageAmount, so
    // ageAmount 0 → original face, 1 → full elderly shape, and the offset
    // rides ON TOP of expressions (smiles keep working).
    const vertexShader = [
      'precision mediump float;',
      'attribute vec3 position;',
      'attribute vec2 uv;',
      'attribute vec3 morph;',
      'uniform mat4 modelViewMatrix;',
      'uniform mat4 projectionMatrix;',
      'uniform vec3 uMorphRight;',
      'uniform vec3 uMorphUp;',
      'uniform vec3 uMorphFwd;',
      'uniform float uMorphScale;',
      'varying vec2 vUv;',
      'varying vec2 vScreenPos;',
      'void main() {',
      '  vUv = uv;',
      '  // vScreenPos = the UNDEFORMED tracked position: the fragment shader',
      '  // samples the live camera there and draws those pixels at the',
      '  // DEFORMED position below — that is what makes the geometric aging',
      '  // actually move the user\\'s own face pixels (mesh-warp), instead of',
      '  // only moving an invisible overlay. Boundary vertices have zero',
      '  // morph, so the warped face blends seamlessly into the un-warped',
      '  // video around it.',
      '  vScreenPos = position.xy;',
      '  vec3 displaced = position + (uMorphRight * morph.x + uMorphUp * morph.y + uMorphFwd * morph.z) * uMorphScale;',
      '  gl_Position = projectionMatrix * modelViewMatrix * vec4(displaced, 1.0);',
      '}',
    ].join('\\n')

    // HYBRID TEXTURE-BASED WRINKLES: the procedural crease()/leftSideCreases()
    // GLSL that used to live here was baked offline into wrinkle_mask.png
    // (same control points, weights, and core+halo falloff — see the bake
    // script header in src/lib/wrinkleTextures.ts). The shader now only
    // SAMPLES that mask and drives shadow/highlight/spots/pores from its
    // channels — it never draws the texture directly on screen.
    //   wrinkleMask.r = crease shadow   wrinkleMask.g = crease highlight
    //   wrinkleMask.b = age spots       detailMap     = tiling pore grain
    const fragmentShader = [
      'precision mediump float;',
      'uniform sampler2D wrinkleMask;',
      'uniform sampler2D detailMap;',
      'uniform sampler2D cameraMap;',
      'uniform float uCoverScale;',
      'uniform float uCropX;',
      'uniform float uCropY;',
      'uniform float uVideoW;',
      'uniform float uVideoH;',
      'uniform float uScreenW;',
      'uniform float uMirror;',
      'uniform float wrinkleStrength;',
      'uniform float wrinkleScale;',
      'uniform float wrinkleSharpness;',
      'uniform float wrinkleDarkness;',
      'uniform float wrinkleHighlight;',
      'uniform float ageAmount;',
      'uniform float wrinkleDebugMode;',
      'varying vec2 vUv;',
      'varying vec2 vScreenPos;',
      '',
      '// Soft 1-inside/0-outside mask, used to keep creases off the eyes,',
      '// nostrils and mouth. The same exclusions are ALSO baked into the',
      '// mask texture — this in-shader copy is belt-and-suspenders for the',
      '// boundary pixels right at the edge of the real mesh holes.',
      'float ellipseMask(vec2 uv, vec2 center, vec2 radius, float feather) {',
      '  vec2 d = (uv - center) / radius;',
      '  float r = length(d);',
      '  return 1.0 - smoothstep(1.0 - feather, 1.0, r);',
      '}',
      'void main() {',
      '  vec2 uv = vUv;',
      '  // Live camera pixels at the UNDEFORMED tracked position — replayed',
      '  // at the deformed one (mesh-warp). Inverse of lmToScreen\\'s cover',
      '  // crop + selfie mirror.',
      '  float sx = vScreenPos.x;',
      '  float sy = -vScreenPos.y;',
      '  if (uMirror > 0.5) sx = uScreenW - sx;',
      '  vec2 vidUv = vec2((sx + uCropX) / (uCoverScale * uVideoW), (sy + uCropY) / (uCoverScale * uVideoH));',
      '  vec3 cam = texture2D(cameraMap, vidUv).rgb;',
      '  vec3 mask = texture2D(wrinkleMask, uv).rgb;',
      '',
      '  // wrinkleSharpness reshapes the baked falloff: >1 tightens the',
      '  // crease core (gamma < 1 on the mask), <1 spreads it softer.',
      '  float shape = 1.0 / max(0.35, wrinkleSharpness);',
      '  float dark = pow(mask.r, shape);',
      '  float light = pow(mask.g, shape);',
      '  float spots = mask.b;',
      '',
      '  // Domain-warped tiling: two decorrelated low-frequency samples of the',
      '  // detail map perturb the pore-sampling coordinates, so the 256px tile',
      '  // never lines up with itself — repeated tiling stops being readable.',
      '  vec2 warp = vec2(',
      '    texture2D(detailMap, uv * 1.3 + 0.13).r,',
      '    texture2D(detailMap, uv * 1.3 + 0.71).r',
      '  ) - 0.5;',
      '  // Tiling skin-detail texture: fine pores (warped) + two slower blotch',
      '  // fields. blotch varies crease intensity along their length; blotch2',
      '  // drives the warm/cool skin mottling below.',
      '  float pores = texture2D(detailMap, uv * 12.0 * wrinkleScale + warp * 0.6).r;',
      '  float blotch = texture2D(detailMap, uv * 3.0 * wrinkleScale + 0.37).r;',
      '  float blotch2 = texture2D(detailMap, uv * 2.2 * wrinkleScale + vec2(0.61, 0.17)).r;',
      '  float variation = 0.55 + 0.45 * blotch;',
      '  dark *= variation;',
      '  light *= variation;',
      '',
      '  dark *= ageAmount;',
      '  light *= ageAmount;',
      '  spots *= ageAmount;',
      '',
      '  float protect = 0.0;',
      '  protect = max(protect, ellipseMask(uv, vec2(0.3496, 0.6186), vec2(0.115, 0.068), 0.4));',
      '  protect = max(protect, ellipseMask(uv, vec2(0.6504, 0.6186), vec2(0.115, 0.068), 0.4));',
      '  protect = max(protect, ellipseMask(uv, vec2(0.397, 0.4512), vec2(0.038, 0.030), 0.4));',
      '  protect = max(protect, ellipseMask(uv, vec2(0.603, 0.4513), vec2(0.038, 0.030), 0.4));',
      '  protect = max(protect, ellipseMask(uv, vec2(0.5, 0.305), vec2(0.150, 0.105), 0.4));',
      '  dark *= (1.0 - protect);',
      '  light *= (1.0 - protect);',
      '  spots *= (1.0 - protect);',
      '',
      '  // Aged-skin zones: wide, heavily-feathered ellipses over forehead,',
      '  // cheeks and chin (computed procedurally, not from the mask texture,',
      '  // to keep the PNG alpha channel at 255 everywhere — low/zero PNG',
      '  // alpha risks premultiplication precision loss of the RGB data',
      '  // channels on some WebView decoders). This zone carries the overall',
      '  // aged-texture and mottling below at very low alpha.',
      '  float aged = 0.0;',
      '  aged = max(aged, ellipseMask(uv, vec2(0.5, 0.80), vec2(0.30, 0.13), 0.7));',
      '  aged = max(aged, ellipseMask(uv, vec2(0.30, 0.45), vec2(0.13, 0.11), 0.7));',
      '  aged = max(aged, ellipseMask(uv, vec2(0.70, 0.45), vec2(0.13, 0.11), 0.7));',
      '  aged = max(aged, ellipseMask(uv, vec2(0.5, 0.14), vec2(0.15, 0.10), 0.7));',
      '  aged *= (1.0 - protect);',
      '  aged *= ageAmount;',
      '',
      '  if (wrinkleDebugMode > 0.5) {',
      '    float m = clamp(max(max(dark, light), spots), 0.0, 1.0);',
      '    gl_FragColor = vec4(vec3(m), 1.0);',
      '    return;',
      '  }',
      '',
      '  // Clamp AFTER applying wrinkleStrength (not before) — with',
      '  // wrinkleStrength above 1.0 the pre-clamp product can exceed 1.0,',
      '  // which would push the color mixes below past their endpoint colors',
      '  // into overshoot/negative-channel extrapolation.',
      '  float darkA = clamp(dark * wrinkleDarkness * wrinkleStrength, 0.0, 1.0);',
      '  float lightA = clamp(light * wrinkleHighlight * wrinkleStrength, 0.0, 1.0);',
      '',
      '  // Pore grain around creases, age spots AND the aged-skin zones',
      '  // (amplitude +30 percent over the previous build per tuning request).',
      '  float active = clamp(max(max(max(dark, light), spots * 0.8), aged * 0.55) * 3.0, 0.0, 1.0);',
      '  float micro = (pores - 0.5) * 0.13 * active;',
      '  darkA = clamp(darkA + max(0.0, micro), 0.0, 1.0);',
      '  lightA = clamp(lightA + max(0.0, -micro), 0.0, 1.0);',
      '',
      '  // Age spots: translucent warm-brown pigmentation, edges broken up by',
      '  // the blotch field so they read as skin, not stickers.',
      '  float spotA = clamp(spots * 0.45 * wrinkleStrength * (0.7 + 0.3 * blotch), 0.0, 1.0);',
      '',
      '  // Aged-skin base layer: very subtle warm/cool mottling + grain inside',
      '  // the aged zones, capped at 0.14 alpha so the live camera always',
      '  // dominates — this is what shifts the read from "young skin with',
      '  // lines drawn on" to "aged skin".',
      '  float mottle = blotch2 - 0.5;',
      '  vec3 warmTint = vec3(0.80, 0.62, 0.50);',
      '  vec3 coolTint = vec3(0.62, 0.64, 0.70);',
      '  vec3 skinTint = mix(coolTint, warmTint, clamp(0.5 + mottle * 1.6, 0.0, 1.0));',
      '  float skinA = aged * (0.05 + 0.10 * abs(mottle) * 2.0 + 0.06 * abs(pores - 0.5) * 2.0);',
      '  skinA = min(skinA * clamp(wrinkleStrength * 0.6, 0.0, 1.0), 0.14);',
      '',
      '  // Warm skin-tone colors — never black or white. Shadow is a muted',
      '  // brown a shade darker than skin (ambient-occlusion tint, not ink);',
      '  // highlight is a faint warm sheen; spots sit between the two.',
      '  vec3 shadowColor = vec3(0.42, 0.30, 0.24);',
      '  vec3 ridgeColor = vec3(0.92, 0.82, 0.70);',
      '  vec3 spotColor = vec3(0.55, 0.42, 0.30);',
      '  // Layered over-composite, bottom to top: mottled skin base, ridge',
      '  // highlight, age spots, crease shadow.',
      '  vec3 outColor = skinTint;',
      '  float outAlpha = skinA;',
      '  outColor = mix(outColor, ridgeColor, lightA);',
      '  outAlpha = lightA + outAlpha * (1.0 - lightA);',
      '  outColor = mix(outColor, spotColor, spotA);',
      '  outAlpha = spotA + outAlpha * (1.0 - spotA);',
      '  outColor = mix(outColor, shadowColor, darkA);',
      '  outAlpha = darkA + outAlpha * (1.0 - darkA);',
      '  // Composite the wrinkle overlay onto the WARPED camera pixels and',
      '  // output opaque — inside the mesh we now REPLACE the background',
      '  // video (that replacement is the visible geometric aging).',
      '  vec3 finalColor = mix(cam, outColor, outAlpha);',
      '  gl_FragColor = vec4(finalColor, 1.0);',
      '}',
    ].join('\\n')

    const gl = renderer.getContext()
    const shaderDiag = compileDiagnostic(gl, vertexShader, fragmentShader)
    const glErrorAfterCompile = glErrorName(gl, gl.getError())

    // Texture loads go through THREE.TextureLoader → an <img> element, which
    // (unlike fetch(), blocked on the file: scheme in Android WebView) reads
    // same-origin file:// siblings of index.html without issue — same
    // pipeline the GLB loads deliberately avoid via XHR, but images never
    // had that restriction. flipY=false everywhere, matching this file's
    // single UV convention: the PNGs are baked with row 0 = v0 = chin.
    const texLoader = new THREE.TextureLoader()
    const texLoaded = (name) => (tex) => {
      rnPost({ type: 'diag', stage: 'wrinkle-texture-loaded', texture: name, width: tex.image.width, height: tex.image.height })
    }
    const texFailed = (name) => () => {
      rnPost({ type: 'error', message: 'wrinkle texture failed to load: ' + name })
    }
    wrinkleMaskTexture = texLoader.load('./wrinkle_mask.png', texLoaded('wrinkle_mask'), undefined, texFailed('wrinkle_mask'))
    wrinkleMaskTexture.flipY = false
    detailTexture = texLoader.load('./wrinkle_detail.png', texLoaded('wrinkle_detail'), undefined, texFailed('wrinkle_detail'))
    detailTexture.flipY = false
    // Live camera feed as a texture — the mesh-warp's pixel source. flipY
    // false: vidUv is computed top-origin in the fragment shader, matching
    // the raw video rows directly.
    cameraVideoTexture = new THREE.VideoTexture(videoEl)
    cameraVideoTexture.flipY = false
    // The detail texture tiles (sampled at uv * 12 in-shader) — RepeatWrapping
    // is required or every sample outside [0,1] clamps to the edge texel.
    // 256×256 is power-of-two, so repeat+mipmaps are legal even in WebGL1.
    detailTexture.wrapS = THREE.RepeatWrapping
    detailTexture.wrapT = THREE.RepeatWrapping

    agingMaterial = new THREE.RawShaderMaterial({
      uniforms: {
        wrinkleMask: { value: wrinkleMaskTexture },
        detailMap: { value: detailTexture },
        cameraMap: { value: cameraVideoTexture },
        uCoverScale: { value: 1 },
        uCropX: { value: 0 },
        uCropY: { value: 0 },
        uVideoW: { value: 1280 },
        uVideoH: { value: 720 },
        uScreenW: { value: W },
        uMirror: { value: 1 },
        uMorphRight: { value: new THREE.Vector3(1, 0, 0) },
        uMorphUp: { value: new THREE.Vector3(0, 1, 0) },
        uMorphFwd: { value: new THREE.Vector3(0, 0, 1) },
        uMorphScale: { value: 0 },
        wrinkleStrength: { value: WRINKLE_DEFAULTS.wrinkleStrength },
        wrinkleScale: { value: WRINKLE_DEFAULTS.wrinkleScale },
        wrinkleSharpness: { value: WRINKLE_DEFAULTS.wrinkleSharpness },
        wrinkleDarkness: { value: WRINKLE_DEFAULTS.wrinkleDarkness },
        wrinkleHighlight: { value: WRINKLE_DEFAULTS.wrinkleHighlight },
        ageAmount: { value: WRINKLE_DEFAULTS.ageAmount },
        wrinkleDebugMode: { value: WRINKLE_DEBUG_MODE ? 1.0 : 0.0 },
      },
      vertexShader,
      fragmentShader,
      transparent: true,
      // false, not the checker milestone's true: this material is now a
      // transparent overlay (creases only; everywhere else is alpha 0, real
      // camera pixels show through), and depth-writing a mostly-transparent
      // surface is the standard case where three.js recommends
      // depthWrite:false to avoid it fighting anything drawn after it.
      depthWrite: false,
      depthTest: true,
      side: THREE.DoubleSide,
    })

    agingMesh = new THREE.Mesh(geo, agingMaterial)
    agingMesh.frustumCulled = false
    agingMesh.renderOrder = 2
    agingMesh.visible = false
    scene.add(agingMesh)

    rnPost({
      type: 'diag',
      stage: 'ensureAgingMesh',
      shaderCompile: shaderDiag,
      glErrorAfterCompile: glErrorAfterCompile,
      vertexCount: AGING_VERTS,
      indexCount: indexTriangles.length,
      uvCount: CANONICAL.uv.length / 2,
      debugTopologyPreviewEnabled: DEBUG_TOPOLOGY_PREVIEW,
      topologyPreview: topologyPreview,
      wrinkleDebugMode: WRINKLE_DEBUG_MODE,
      wrinkleUniforms: WRINKLE_DEFAULTS,
      morph: {
        maxDispMm: Math.round(morphBuild.maxDispMm * 100) / 100,
        affectedVerts: morphBuild.affectedVerts,
        boundaryVerts: morphBuild.boundaryVerts,
        canonTempleCm: Math.round(CANON_TEMPLE_CM * 100) / 100,
      },
    })
  } catch (e) {
    rnPost({ type: 'error', message: 'ensureAgingMesh failed: ' + (e && (e.stack || e.message) || e) })
  }
}

let agingDiagSent = false
let postRenderDiagSent = false

function updateAgingMesh(landmarks) {
  try {
    ensureAgingMesh()
    if (!agingMesh) return
    const li = CANONICAL.landmarkIndex
    for (let slot = 0; slot < li.length; slot++) {
      lmToScreen(landmarks[li[slot]], _av)
      agingPositions[slot * 3] = _av.x
      agingPositions[slot * 3 + 1] = _av.y
      agingPositions[slot * 3 + 2] = _av.z + 1
    }
    // Geometric aging: rotate the face-local morph basis with the tracked
    // head (same smoothed rig the accessories use — no extra smoothing
    // layer, so no extra latency, and stability equals the rig's) and scale
    // canonical cm → screen px × ageAmount. The vertex shader applies it.
    _morphRight.set(1, 0, 0).applyQuaternion(rig.quaternion)
    _morphUp.set(0, 1, 0).applyQuaternion(rig.quaternion)
    _morphFwd.set(0, 0, 1).applyQuaternion(rig.quaternion)
    agingMaterial.uniforms.uMorphRight.value.copy(_morphRight)
    agingMaterial.uniforms.uMorphUp.value.copy(_morphUp)
    agingMaterial.uniforms.uMorphFwd.value.copy(_morphFwd)
    agingMaterial.uniforms.uMorphScale.value =
      (rig.faceWidth / CANON_TEMPLE_CM) * agingMaterial.uniforms.ageAmount.value
    // Camera-warp mapping: keep the fragment shader's inverse-lmToScreen in
    // sync with the live cover-crop and mirror state every frame.
    agingMaterial.uniforms.uCoverScale.value = _cover.scale
    agingMaterial.uniforms.uCropX.value = _cover.cropX
    agingMaterial.uniforms.uCropY.value = _cover.cropY
    agingMaterial.uniforms.uVideoW.value = _cover.vw
    agingMaterial.uniforms.uVideoH.value = _cover.vh
    agingMaterial.uniforms.uScreenW.value = W
    agingMaterial.uniforms.uMirror.value = facing === 'user' ? 1 : 0
    agingMesh.geometry.attributes.position.needsUpdate = true
    agingMesh.visible = true

    if (!agingDiagSent) {
      agingDiagSent = true
      agingMesh.geometry.computeBoundingBox()
      const bb = agingMesh.geometry.boundingBox
      const worldPos = new THREE.Vector3()
      agingMesh.getWorldPosition(worldPos)
      const gl = renderer.getContext()
      rnPost({
        type: 'diag',
        stage: 'updateAgingMesh-first-frame',
        boundingBoxMin: bb ? [bb.min.x, bb.min.y, bb.min.z] : null,
        boundingBoxMax: bb ? [bb.max.x, bb.max.y, bb.max.z] : null,
        meshWorldPosition: [worldPos.x, worldPos.y, worldPos.z],
        meshVisible: agingMesh.visible,
        glErrorAfterPositionUpdate: glErrorName(gl, gl.getError()),
        rigFaceWidth: rig.faceWidth,
        rigPosition: [rig.position.x, rig.position.y, rig.position.z],
      })
    }
  } catch (e) {
    rnPost({ type: 'error', message: 'updateAgingMesh failed: ' + (e && (e.stack || e.message) || e) })
  }
}

// ── Face occluder (depth-only): hides accessory parts behind the head ──────
// Skipped while the aging mesh is active — that mesh IS a full, opaque face
// surface and already wins the depth test for anything behind it.
let triangles = null
let occluderMesh = null
const occPositions = new Float32Array(468 * 3)
const _v = new THREE.Vector3()

function updateOccluder(landmarks) {
  if (!triangles) {
    const pts = new Float64Array(468 * 2)
    for (let i = 0; i < 468; i++) { pts[i * 2] = landmarks[i].x; pts[i * 2 + 1] = landmarks[i].y }
    triangles = new Delaunay(pts).triangles.slice()
    const geo = new THREE.BufferGeometry()
    geo.setAttribute('position', new THREE.BufferAttribute(occPositions, 3))
    geo.setIndex(new THREE.BufferAttribute(triangles, 1))
    occluderMesh = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({ colorWrite: false }))
    occluderMesh.renderOrder = -1
    occluderMesh.frustumCulled = false
    scene.add(occluderMesh)
  }
  for (let i = 0; i < 468; i++) {
    lmToScreen(landmarks[i], _v)
    occPositions[i * 3] = _v.x
    occPositions[i * 3 + 1] = _v.y
    occPositions[i * 3 + 2] = _v.z
  }
  occluderMesh.geometry.attributes.position.needsUpdate = true
  occluderMesh.visible = true
}

// ── Per-frame placement ─────────────────────────────────────────────────────
const _offset = new THREE.Vector3()

function placeFilter() {
  const def = FILTERS[currentFilter]
  if (!def || !filterRoot.children.length) { filterRoot.visible = false; return }
  filterRoot.visible = true
  _offset.set(def.offset[0], def.offset[1], def.offset[2])
    .multiplyScalar(rig.faceWidth)
    .applyQuaternion(rig.quaternion)
  filterRoot.position.copy(rig.position).add(_offset)
  filterRoot.quaternion.copy(rig.quaternion)
  filterRoot.scale.setScalar(rig.faceWidth)
}

// ── MediaPipe (Tasks Vision) lifecycle ──────────────────────────────────────
let frameCount = 0

async function startCamera() {
  videoEl.classList.toggle('mirrored', facing === 'user')
  videoStream = await realGUM({ video: true })
  if (isDestroyed()) { videoStream.getTracks().forEach((t) => t.stop()); return }
  videoEl.srcObject = videoStream
  await new Promise((resolve) => {
    if (videoEl.readyState >= 2) return resolve()
    videoEl.onloadeddata = () => resolve()
  })
  try { await videoEl.play() } catch (e) {}
}

async function stopCamera() {
  try { if (videoStream) videoStream.getTracks().forEach((t) => t.stop()) } catch (e) {}
  videoStream = null
  try { if (videoEl.srcObject) videoEl.srcObject.getTracks().forEach((t) => t.stop()) } catch (e) {}
  videoEl.srcObject = null
}

function detectFrame() {
  if (isDestroyed() || !faceLandmarker) return
  frameCount += 1
  if (frameCount % PROCESS_EVERY !== 0) return
  const image = trackingFrame()
  if (!image) return
  // detectForVideo requires a strictly increasing timestamp (ms).
  detectTimestamp = Math.max(detectTimestamp + 1, Math.round(performance.now()))
  try {
    latestResult = faceLandmarker.detectForVideo(image, detectTimestamp)
  } catch (e) {
    return
  }
  const found = !!(latestResult && latestResult.faceLandmarks && latestResult.faceLandmarks.length)
  latestLandmarks = found ? latestResult.faceLandmarks[0] : null
  if (found !== trackingFound) {
    trackingFound = found
    if (found) rig.fresh = true
    rnPost({ type: 'tracking', found })
  }
}

async function startAR() {
  try {
    rnPost({ type: 'loading', label: 'mediapipe' })
    const vision = await FilesetResolver.forVisionTasks(
      'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.9/wasm',
    )
    if (isDestroyed()) return
    faceLandmarker = await FaceLandmarker.createFromOptions(vision, {
      baseOptions: {
        modelAssetPath: 'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',
        delegate: TIER === 2 ? 'GPU' : 'CPU',
      },
      runningMode: 'VIDEO',
      numFaces: 1,
      outputFaceBlendshapes: true,
      outputFacialTransformationMatrixes: false,
      minFaceDetectionConfidence: 0.5,
      minTrackingConfidence: 0.5,
    })
    if (isDestroyed()) return

    rnPost({ type: 'loading', label: 'model' })
    await showFilter(currentFilter)
    if (isDestroyed()) return

    rnPost({ type: 'loading', label: 'camera' })
    await startCamera()
    if (isDestroyed()) { await stopCamera(); return }

    // Bumped once, here, right before the very first frame — if this ever
    // reads > 1 in a diag payload it means startAR()/loop() ran twice in
    // this same runtime, which the animationLoopGeneration check below
    // treats as a hard stop rather than letting two loops render concurrently.
    animationLoopGeneration += 1
    const myLoopGeneration = animationLoopGeneration
    rnPost({
      type: 'diag',
      stage: 'animation-loop-start',
      animationLoopGeneration: myLoopGeneration,
      webArInitializationCount: WEB_AR_INIT_COUNT,
    })
    const loop = () => {
      if (isDestroyed()) return
      if (myLoopGeneration !== animationLoopGeneration) {
        // A newer startAR() call began its own loop — this one must not
        // keep rendering (that would be the "second animation loop" bug
        // this investigation is guarding against). Self-cancel silently.
        return
      }
      rafId = requestAnimationFrame(loop)
      window.__WEB_AR_RUNTIME__.animationFrameId = rafId
      detectFrame()
      if (latestLandmarks) {
        updateCover()
        updateRig(latestLandmarks)
        if (currentFilter === 'grandpa') {
          updateAgingMesh(latestLandmarks)
          if (occluderMesh) occluderMesh.visible = false
        } else {
          if (agingMesh) agingMesh.visible = false
          updateOccluder(latestLandmarks)
        }
        placeFilter()
      } else {
        filterRoot.visible = false
        if (occluderMesh) occluderMesh.visible = false
        if (agingMesh) agingMesh.visible = false
      }
      // Framebuffer-clear investigation: force a full color/depth/stencil
      // clear on every frame, unconditionally, ahead of the render call —
      // independent of renderer.autoClear (confirmed true / unmodified
      // three.js default throughout this file). setRenderTarget(null) and
      // setScissorTest(false) rule out the two other ways a clear could
      // silently miss pixels: rendering into a leftover render target, or a
      // leftover scissor rect restricting the clear to less than the full
      // canvas. Neither is ever set anywhere else in this file (verified),
      // so this is defensive, not a fix for a located misconfiguration.
      renderer.setRenderTarget(null)
      renderer.setScissorTest(false)
      renderer.clear(true, true, true)
      if (renderDiagFramesRemaining > 0) {
        rnPost({
          type: 'diag',
          stage: 'pre-render',
          activeFilterId: currentFilter,
          sceneChildCount: scene.children.length,
          filterOwnedCount: countFilterOwned(),
          rendererInfoRenderCalls: renderer.info.render.calls,
          renderTarget: renderer.getRenderTarget() === null ? 'null (default framebuffer)' : 'non-null',
          autoClear: renderer.autoClear,
          autoClearColor: renderer.autoClearColor,
          autoClearDepth: renderer.autoClearDepth,
          autoClearStencil: renderer.autoClearStencil,
        })
      }
      renderer.render(scene, camera3)
      if (renderDiagFramesRemaining > 0) {
        renderDiagFramesRemaining -= 1
        rnPost({
          type: 'diag',
          stage: 'post-render-clear-check',
          activeFilterId: currentFilter,
          sceneChildCount: scene.children.length,
          filterOwnedCount: countFilterOwned(),
          rendererInfoRenderCalls: renderer.info.render.calls,
          renderTarget: renderer.getRenderTarget() === null ? 'null (default framebuffer)' : 'non-null',
        })
      }
      if (agingMesh && agingMesh.visible && !postRenderDiagSent) {
        postRenderDiagSent = true
        const gl = renderer.getContext()
        const renderGlError = glErrorName(gl, gl.getError())
        rnPost({
          type: 'diag',
          stage: 'post-render',
          status: renderGlError === 'NO_ERROR' ? 'RENDERED' : 'RENDER_ERROR',
          glErrorAfterRender: renderGlError,
        })
      }
      if (compositeCtx) compositeFrame()
    }
    loop()
    rnPost({
      type: 'ready',
      animationLoopActive: true,
      animationLoopGeneration: myLoopGeneration,
      webArInitializationCount: WEB_AR_INIT_COUNT,
    })
  } catch (e) {
    rnPost({ type: 'error', message: 'start: ' + (e && e.message || e) })
  }
}

async function stopAR() {
  cancelAnimationFrame(rafId)
  try { await stopCamera() } catch (e) {}
  try { faceLandmarker && faceLandmarker.close() } catch (e) {}
  faceLandmarker = null
  latestLandmarks = null
  latestResult = null
}

/** Full, idempotent teardown — every requirement from the crash investigation. */
async function destroyAll() {
  if (isDestroyed()) return
  window.__kidtokDestroyed = true
  cancelAnimationFrame(rafId)
  window.removeEventListener('resize', resize)
  try { await stopCamera() } catch (e) {}
  try { faceLandmarker && faceLandmarker.close() } catch (e) {}
  faceLandmarker = null
  try { if (recorder && recorder.state !== 'inactive') recorder.stop() } catch (e) {}
  recorder = null
  try { micStream && micStream.getTracks().forEach((t) => t.stop()) } catch (e) {}
  micStream = null
  try { compositeStream && compositeStream.getTracks().forEach((t) => t.stop()) } catch (e) {}
  compositeStream = null
  try { audioCtx && audioCtx.state !== 'closed' && audioCtx.close() } catch (e) {}
  audioCtx = null
  recDest = null
  // Real GPU-resource disposal happens exactly once, here, at full teardown
  // — never per filter-switch (see the warning in clearActiveFilter() for
  // why disposing a clone's shared geometry/material would be wrong).
  try {
    for (const id of Object.keys(modelTemplates)) disposeObject3D(modelTemplates[id])
    disposeObject3D(agingMesh)
    disposeObject3D(occluderMesh)
    if (wrinkleMaskTexture) wrinkleMaskTexture.dispose()
    if (detailTexture) detailTexture.dispose()
    if (cameraVideoTexture) cameraVideoTexture.dispose()
  } catch (e) {}
  try { renderer.dispose() } catch (e) {}
  try { window.removeEventListener('message', listenRN) } catch (e) {}
  try { document.removeEventListener('message', listenRN) } catch (e) {}
  if (window.__WEB_AR_RUNTIME__) window.__WEB_AR_RUNTIME__.destroyed = true
}
window.addEventListener('pagehide', () => { destroyAll() })
window.addEventListener('beforeunload', () => { destroyAll() })

// ── Recording (composite canvas + WebAudio mic) ─────────────────────────────
function ensureAudioCtx() {
  if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)()
  if (audioCtx.state === 'suspended') audioCtx.resume()
  return audioCtx
}

function compositeFrame() {
  if (!compositeCtx) return
  const w = compositeCanvas.width, h = compositeCanvas.height
  const vw = videoEl.videoWidth, vh = videoEl.videoHeight
  if (!vw || !vh) return
  const videoAspect = vw / vh
  const outAspect = w / h
  let sw, sh, sx, sy
  if (videoAspect > outAspect) { sh = vh; sw = sh * outAspect; sx = (vw - sw) / 2; sy = 0 }
  else { sw = vw; sh = sw / outAspect; sx = 0; sy = (vh - sh) / 2 }
  if (facing === 'user') {
    compositeCtx.save()
    compositeCtx.scale(-1, 1)
    compositeCtx.drawImage(videoEl, sx, sy, sw, sh, -w, 0, w, h)
    compositeCtx.restore()
  } else {
    compositeCtx.drawImage(videoEl, sx, sy, sw, sh, 0, 0, w, h)
  }
  compositeCtx.drawImage(renderer.domElement, 0, 0, w, h)
}

function pickMime() {
  const candidates = ['video/mp4;codecs=avc1', 'video/mp4', 'video/webm;codecs=vp8,opus', 'video/webm']
  for (const c of candidates) { try { if (MediaRecorder.isTypeSupported(c)) return c } catch (e) {} }
  return ''
}

async function startRecording() {
  if (recorder || isDestroyed()) return
  try {
    const scaleDown = TIER === 2 ? 1 : 1.5
    compositeCanvas = document.createElement('canvas')
    compositeCanvas.width = Math.round(720 / scaleDown)
    compositeCanvas.height = Math.round((720 / scaleDown) * (H / W))
    compositeCtx = compositeCanvas.getContext('2d')
    compositeStream = compositeCanvas.captureStream(30)
    try {
      micStream = await realGUM({ audio: true })
      if (isDestroyed()) { micStream.getTracks().forEach((t) => t.stop()); return }
      const ctx = ensureAudioCtx()
      recDest = ctx.createMediaStreamDestination()
      ctx.createMediaStreamSource(micStream).connect(recDest)
      recDest.stream.getAudioTracks().forEach((t) => compositeStream.addTrack(t))
    } catch (e) {
      rnPost({ type: 'error', message: 'mic: ' + (e && e.message || e) })
    }
    const mime = pickMime()
    recordedChunks = []
    recorder = new MediaRecorder(compositeStream, mime ? { mimeType: mime, videoBitsPerSecond: 4_000_000 } : undefined)
    recorder.ondataavailable = (e) => { if (e.data && e.data.size) recordedChunks.push(e.data) }
    recorder.onstop = () => { deliverRecording().catch((e) => rnPost({ type: 'error', message: 'deliver: ' + (e && e.message || e) })) }
    recorder.start(1000)
    rnPost({ type: 'videoStart' })
  } catch (e) {
    recorder = null
    rnPost({ type: 'error', message: 'record-start: ' + (e && e.message || e) })
  }
}

function stopRecording() {
  if (!recorder) return
  try { recorder.stop() } catch (e) { rnPost({ type: 'error', message: 'stop: ' + (e && e.message || e) }) }
}

async function deliverRecording() {
  const mime = recorder && recorder.mimeType ? recorder.mimeType : 'video/webm'
  recorder = null
  compositeCtx = null
  try { micStream && micStream.getTracks().forEach((t) => t.stop()) } catch (e) {}
  micStream = null
  recDest = null
  const blob = new Blob(recordedChunks, { type: mime })
  recordedChunks = []
  if (isDestroyed()) return
  const buffer = await blob.arrayBuffer()
  if (isDestroyed()) return
  const bytes = new Uint8Array(buffer)
  let binary = ''
  const SLICE = 0x8000
  for (let i = 0; i < bytes.length; i += SLICE) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + SLICE))
  }
  const base64 = btoa(binary)
  const CHUNK = 256 * 1024
  const total = Math.ceil(base64.length / CHUNK)
  for (let i = 0; i < total; i++) {
    if (isDestroyed()) return
    rnPost({ type: 'videoChunk', index: i, total, data: base64.substr(i * CHUNK, CHUNK) })
  }
  rnPost({ type: 'videoDone', mime, size: blob.size })
}

// ── Control messages ────────────────────────────────────────────────────────
async function handleMessage(raw) {
  if (isDestroyed()) return
  let msg
  try { msg = JSON.parse(raw) } catch (e) { return }
  try {
    if (msg.type === 'setAnimal') {
      await showFilter(msg.id)
    } else if (msg.type === 'record') {
      if (msg.on) await startRecording()
      else stopRecording()
    } else if (msg.type === 'flip') {
      facing = facing === 'user' ? 'environment' : 'user'
      rnPost({ type: 'loading', label: 'flip' })
      latestLandmarks = null
      await stopCamera()
      if (isDestroyed()) return
      await startCamera()
      if (isDestroyed()) return
      rnPost({ type: 'ready' })
    } else if (msg.type === 'destroy') {
      await destroyAll()
    }
  } catch (e) {
    rnPost({ type: 'error', message: 'message ' + msg.type + ': ' + (e && e.message || e) })
  }
}

window.__kidtokHandle = handleMessage
for (const queued of window.__kidtokQueue) handleMessage(queued)
window.__kidtokQueue = []

startAR()
</script>
</body>
</html>`
